# Generated by Django 5.1.7 on 2025-04-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.CharField(max_length=100, verbose_name="疾病名称")),
                ("symptoms", models.TextField(verbose_name="典型症状")),
                ("check_items", models.TextField(verbose_name="建议检查")),
                ("advice", models.TextField(verbose_name="处理建议")),
            ],
        ),
    ]
